server:
  address: ${HOST_IP}
  port: ${HOST_PORT}

database:
  host: "${DATABASE_HOST}"
  user: "${DATABASE_USER}"
  password: "${DATABASE_PASSWORD}"
  database: "${DATABASE_NAME}"
  scheme: "${DATABASE_SCHEME}"
  port: "${DATABASE_PORT}"
  connectionTimeoutMillis: 2000
  max: 100

logging:
  level: ${LOGGING_LEVEL}

setting:
  accessKey: ${ACCESS_KEY}
  agent: ${AGENT_PK}
  network: ${NETWORK}
  delaySecond: ${DELAY_SECOND}
  whiteList: ${WHITE_LIST}
  rpcEndpoint: ${RPC_ENDPOINT}
  inquiryLimit: ${INQUIRY_LIMIT}

provision:
  items:

scheduler:
  enable: true
  items:
    - name: postback
      enable: true
      expression: "*/1 * * * * *"
